export const ITEM_DETAILS = 'item-details'
export const PACKAGE_SCREEN = 'package-screen'
export const PACKAGE_DETAILS = 'package-details'
export const ITEM_ORDER_DETAILS = 'order-details'
export const COMPLAIN_CREATE_SCREEN = 'create-complain'
export const OFFERS = "الباقات"
export const HOME = "ألرئيسيه"
export const  ORDER_SUCCESS_SCREEN = "OrderSuccessScreen"
export const ORDERS = ("حاليه")
export const COMPLETE_ORDER_DETAILS = ("طلبات تم تنفيذها")
export const ORDERS_DETAILS = (" تفاصيل جاري تنفيذها")
export const PREVIOUS_ORDERS = ("سابقه")
export const MANUAL_LOCATION_ADD = "manual-location-screen"
export const ORDER_SELECT_LOCATION = "select-location-screen"
export const ORDER_SELECT_REGION= "select-region-screen"
export const ORDER_COMFIRM_DETAILS= "comfirm-order-details-screen"
export const MY_ORDERS = ('طلباتي')
export const CART = "CartScreen"
export const MAP = "MapScreen"
export const CHAT_ROOM = "chat-room-screen"
