export const ITEM_DETAILS = 'item-details'
export const PACKAGE_SCREEN = 'package-screen'
export const PACKAGE_DETAILS = 'package-details'
export const ITEM_ORDER_DETAILS = 'order-details'
export const COMPLAIN_CREATE_SCREEN = 'create-complain'
export const COMPLAIN_ORDER_DETAILS= 'complain-details'
export const OFFERS = "Packages"
export const ACCOUNT = "Account"
export const HOME = "Home"
export const  ORDER_SUCCESS_SCREEN = "OrderSuccessScreen"
export const COMPLETE_ORDER_DETAILS = ("طلبات تم تنفيذها")
export const ORDERS_DETAILS = ("Current")
export const PREVIOUS_ORDERS = ("Previous")
export const ORDERS = ("Current")
export const OFFERS_SCREEN = ("OFFERS_SCREEN}")
export const MANUAL_LOCATION_ADD = "manual-location-screen"
export const ORDER_SELECT_LOCATION = "select-location-screen"
export const ORDER_SELECT_REGION= "select-region-screen"
export const ORDER_COMFIRM_DETAILS= "comfirm-order-details-screen"
export const MY_ORDERS = ('Orders')
export const CART = "CartScreen"
export const MAP = "MapScreen"
export const REVIEW_ORDER_SCREEN = "review-order"
export const CHAT_ROOM = "chat-room-screen"
export const CURRENCY = " ر.س"
export const Offer_route_name="العروض"
export const CHANGE_ORDER_DATE = 'ChangeDateOrderScreen'
export const NO_CONNECTION_SCREEN="noconnection"
export const CHAT_ROOM_fireBase = " chatroomfirebase"
export const SELECT_LAN = "SelectLanguageScreen"